### ISSUE TITLE
[PlotCraft] 进度

### ISSUE THREAD

**Issue by engsr6982** [engsr6982/PlotCraft#1]
# Tasks

## 核心

- [x] PlotPos
- [x] PlotDimension
- [x] PlotGenerator
- [x] CustomGenerator
- [x] CustomGeneratorHeight

## 数据

- [x] Config
- [x] PlotDB
- [x] PlotDBImpl
- [x] PlayerNameDB
- [x] EconomicQueue

## 事件

- [x] 拦截基础事件
- [x] 地皮自定义事件

## 功能

- [x] 地皮购买
- [x] 地皮出售
- [x] 地皮共享
- [x] 地皮传送
- [x] 地皮评论
- [x] 地皮内飞行
- [x] 地皮市场（玩家）
- [x] 在线更改传送点

## 命令

> 部分功能比较复杂，使用表单操作
- [x] /plo
- [x] /plo plot
- [x] /plo <op|deop> <realName>
- [x] /plo go <overworld | plot>

## Other

- [x] __dllexport
- [x] Release Add SDK.zip
- [x] RemoteCall LSE (部分API)

**Comment by quizhizhe** [comment]
终于有人用来开发地皮系统，类目了，这里有个[generator-terrain](https://github.com/LiteLDev/MoreDimensions/tree/develop/src/test/generator/generator-terrain) 是我之前测试生成器的示例，里面是类似地皮系统的地形，相较于loadchunk内使用 levelchunk.setBlock来设置地形会快好多，对服务器的性能要求压力也小
![屏幕截图 2024-03-01 204138](https://github.com/engsr6982/PlotCraft/assets/42761326/31852390-299b-4cb3-8631-da32249f4292)

**Comment by engsr6982** [comment]
> 终于有人用来开发地皮系统，类目了，这里有个[generator-terrain](https://github.com/LiteLDev/MoreDimensions/tree/develop/src/test/generator/generator-terrain) 是我之前测试生成器的示例，里面是类似地皮系统的地形，也许有一些可以参考的地方。这个是相较于loadchunk内使用 levelchunk.setBlock来设置地形会快好多，对服务器的性能要求压力也小 ![屏幕截图 2024-03-01 204138](https://private-user-images.githubusercontent.com/42761326/336668821-31852390-299b-4cb3-8631-da32249f4292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjM0NjIsIm5iZiI6MTcxNzU2MzE2MiwicGF0aCI6Ii80Mjc2MTMyNi8zMzY2Njg4MjEtMzE4NTIzOTAtMjk5Yi00Y2IzLTg2MzEtZGEzMjI0OWY0MjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA0NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZGFkOTM0MjhiZjAyMmYzMThmYTE5ZjA5NzE4ZTEwMjFhMWFkOTMwYTlkOGMyZWVjNmRlYTU0NDc0NzY0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Cx3tgDkILgSZK3YoYPl6oy1w8kmiLm3MRF_TXfjCQ0)

看样子不错。

![5dfcf1aed4d79c8b7b9dfc5b94b21a0c](https://github.com/engsr6982/PlotCraft/assets/109733049/143131a0-0fb3-409e-a02a-4fac478328ef)
目前我这个setBlock测试效果还可以，把地皮内的草方块去掉用超平坦的的草方块可以省掉一部分setblock
目前不知道从哪设置超平坦的高度

**Comment by engsr6982** [comment]
> 海拔高度还是什么高度？海拔在Dimension里

超平坦的地形高度，超平坦地形默认是4层，不知道从哪调高一些
```cpp
    levelchunk.setBlockVolume(mPrototype, 0); // 设置基础地形
```

**Comment by quizhizhe** [comment]
> > 海拔高度还是什么高度？海拔在Dimension里
> 
> 超平坦的地形高度，超平坦地形默认是4层，不知道从哪调高一些
> 
> ```c++
>     levelchunk.setBlockVolume(mPrototype, 0);
> ```

是设置多几层是吧，得改BlockVolume里面的内容

**Comment by engsr6982** [comment]
> 终于有人用来开发地皮系统，类目了，这里有个[generator-terrain](https://github.com/LiteLDev/MoreDimensions/tree/develop/src/test/generator/generator-terrain) 是我之前测试生成器的示例，里面是类似地皮系统的地形，也许有一些可以参考的地方。这个是相较于loadchunk内使用 levelchunk.setBlock来设置地形会快好多，对服务器的性能要求压力也小
> 
> ![屏幕截图 2024-03-01 204138](https://github.com/engsr6982/PlotCraft/assets/42761326/31852390-299b-4cb3-8631-da32249f4292)
> 
> 

目前有点不理解setBlockVolume的生成逻辑，以及从哪调整世界的地形高度，目前只知道这些信息：
https://github.com/engsr6982/PlotCraft/blob/main/src/plotcraft/core/PlotGenerator2.cc

大佬能指点一下吗？👀

**Comment by quizhizhe** [comment]
这个生成逻辑是这样的
比如原版的超平坦，所有的区块都是一样的，只需要设置一个模板区块是什么样的，生成的时候，直接按照这个模板区块生成即可。
mPrototypeBlocks就是类似于这样模板区块的存在，类比一下
https://github.com/engsr6982/PlotCraft/blob/8080671eff23437e77e57c257ce20b50e9b93496/src/plotcraft/core/PlotGenerator2.h#L12-L19
这些，就是模板区块（后面的_backup是多余的，我测试忘删了）
这些模板区块是以地皮边框的不同形状得来的，四个角，四个边，这样确定好地皮大小后，我们只需对在其边上的区块，直接设置成对应的模板区块即可，这样生成就能设置任意大小的地皮边框（2x2的可能有问题）

这个生成方式是按照区块来生成，所以生成速度上会比较快，并且区块内的方块是在初始化时候就确定了，之后是直接填充，对性能上的压力也小。

然后是虚空的问题，不太明白你说的块与块之间是虚空。我写的这个示例，
所有方块都是在y0基础上生成的，所以y0以下的都会是虚空
这里
https://github.com/engsr6982/PlotCraft/blob/8080671eff23437e77e57c257ce20b50e9b93496/src/plotcraft/core/PlotGenerator2.cc#L132
`setBlockVolume`的最后一个参数0就是设置这个的

调整世界的高度意思是增加方块的层数吗？比如泥土？这个需要更改这里
https://github.com/engsr6982/PlotCraft/blob/5638dab746d9bdbde642c1d2c7cb1d0a7a750881/src/plotcraft/core/PlotGenerator2.h#L12-L19
`mPrototypeBlocks`的内容，并且这些std::vector<Block const*>初始化需要在更改`mPrototypeBlocks`的内容后操作

**Comment by engsr6982** [comment]
”块与块之间是虚空“指的是这个：
![image](https://github.com/engsr6982/PlotCraft/assets/109733049/540b3128-a1ea-4d6c-b233-57aeb6b25942)
代码只执行了最后一个分支（未改动逻辑）
https://github.com/engsr6982/PlotCraft/blob/1a12bd34657f05d6f251b6e2087b1964b2308561/src/plotcraft/core/PlotGenerator2.cc#L165-L167

**Comment by quizhizhe** [comment]
应该是构造BlockVolume时出错了，这个当时我测试也是这个问题，反编译出来会发现。其他if的BlockVolume是只有三个参数。我也不知道这个是怎么触发的

**Comment by engsr6982** [comment]
> 应该是构造BlockVolume时出错了，这个当时我测试也是这个问题，反编译出来会发现。其他if的BlockVolume是只有三个参数。我也不知道这个是怎么触发的。 可以在上面新写一个BlockVolume的构造函数来避免。与原来的参数不同就行。可以顺便提供一下dll和pdb吗？我放进ida看下

[plugins.zip](https://github.com/user-attachments/files/15910625/plugins.zip)

**Comment by quizhizhe** [comment]
好怪，似乎看起来构造没问题，确定是只执行了最后一个if吗？在其他if的条件里放个控制台打印字符的看下？

**Comment by engsr6982** [comment]
> 好怪，似乎看起来构造没问题，确定是只执行了最后一个if吗？在其他if的条件里放个控制台打印字符的看下？

加了log，if分支进入了，但是set没有效果，只有最后一个分支有效果（LOG忘加换行符了）

![image](https://github.com/engsr6982/PlotCraft/assets/109733049/a578da0a-2c09-4e14-ae4c-0ee37964653d)

![image](https://github.com/engsr6982/PlotCraft/assets/109733049/eaeff84e-05d3-4038-96c3-0850263a691e)

***

我在Generator1测试了一下，效果是一样的，感觉这个setBlockVolume没有执行
https://github.com/engsr6982/PlotCraft/blob/644f15c1b2ad4d72dad93fbc9791574fe6997512/src/plotcraft/core/PlotGenerator.cc#L84-L93

**Comment by quizhizhe** [comment]
不是setBlockVolume，应该是构建BlockVolume出了问题，手动写一个实现即可，或者直接更改xmake 的本地package里的也可以

**Comment by engsr6982** [comment]
> 应该不是setBlockVolume没效果，应该是构建BlockVolume出了问题，手动写一个实现即可，或者直接更改xmake 的本地package里的也可以。BlockVolume的成员已经确定，可以手动赋值过去再setBlockVolume试试，如果还是不行的话，只能手动新写一个构造函数了

刚刚验证过了，确实是BlockVolume的问题，拷贝mPrototype再修改成员可以正常的setBlockVolume
