### ISSUE TITLE
[Todo] 优化部分功能

### ISSUE THREAD

**Issue by engsr6982** [engsr6982/PlotCraft#13]
- [x] 细分权限系统
- [x] PlotPos Cube 查询
- [x] #12
- [x] 重写经济系统
- [x] GUI 兼容地皮管理员编辑
- [x] 移除部分无用的代码
- [x] 移除 RemoteCall 部分代码
- [x] 移除 SQLitecpp 依赖（旧数据库转换）
